#! /bin/bash

echo 'Running lint'
echo '------------------------------------'
npm run lint

echo 'Running tests'
echo '------------------------------------'
npm test

echo 'Running test coverage'
echo '------------------------------------'
npm run coverage